---
title: Jayalakshmi Jain
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-paginate
exclude:
- "/vendor/"
subtitle: Projects, tutorials and thoughts on Data Science in general.
email: jlakshmi235@gmail.com
name: Jayalakshmi Jain
description: 'Projects, tutorials and thoughts on Data Science in general.

'
baseurl: ''
url: http://jlakshmi235.github.io
cover: "/assets/header_image.jpg"
logo: "/assets/jj-logo.jpg"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: monokai-sublime
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
social:
- name: Facebook
  icon: facebook
  username: jayalakshmi.jain.1
  url: https://www.facebook.com/jayalakshmi.jain.1
  desc: Friend me on Facebook
  share: true
- name: GitHub
  icon: github
  username: Jlakshmi235
  url: https://github.com/Jlakshmi235
  desc: Fork me on GitHub
  share: false
- name: LinkedIn
  icon: linkedin
  username: Jayalakshmi Jain
  url: https://www.linkedin.com/in/jayalakshmi-jain
  desc: Connect with me on LinkedIn
  share: true
protocols:
  fb_image: "/assets/logo.png"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: "/assets/logo.png"
  os_repo: https://github.com/bencentra/centrarium.com
  os_rcs_type: git
  os_src: git@github.com:bencentra/centrarium.com.git
